
export const SET_RECEIVE = 'SET_RECEIVE'
export const SET_STAR_PEOPLE = 'SET_STAR_PEOPLE'

export const SET_SIGNIN = 'SET_SIGNIN'

export const STORE_MESSAGE_SEND = 'STORE_MESSAGE_SEND'

export const STORE_MESSAGE_IMAGE_SEND = 'STORE_MESSAGE_IMAGE_SEND'

export const SET_FILTER = 'SET_FILTER'


